(in-package #:cl-user)

(defpackage #:cl-libical-tests
  (:use #:cl #:libical))

(in-package #:cl-libical-tests)

(defun split-string (string delimiter)
  (loop with start = 0
        for pos = (position delimiter string :start start)
        collect (subseq string start pos)
        while pos
        do (setf start (+ pos 1))
        finally (subseq string start)))

(defun ical-rules-equal-p (rule1 rule2)
  (labels ((parse-ical (rule)
	     (sort (split-string rule #\;) #'string<)))
    (equal (parse-ical rule1) (parse-ical rule2))))

(defun check-and-print-results (testcases)
  (let ((all-passed t))
    (dolist (pair testcases)
      (let ((test-string (car pair))
	    (description (cdr pair))
	    (checked-str "✅")
	    (crossed-str "❌")
	    result)
	(setq result (icalrecurrencetype-as-string (icalrecurrencetype-from-string test-string)))
	(if (ical-rules-equal-p test-string result)
	    (format t "~a ~s~%" checked-str description)
	    (progn
	      (setf all-passed nil)
	      (format t "~a ~s (FAILED)~%    Expected: ~a~%    Actual:   ~a~%" crossed-str description test-string result)))))
    all-passed))

(defun test-suite ()
  (or
   (check-and-print-results
    '(("FREQ=DAILY;COUNT=10" . "Daily for 10 occurrences")
      ("FREQ=WEEKLY;UNTIL=20230401T235959Z" . "Weekly until April 1, 2023")
      ("FREQ=MONTHLY;INTERVAL=2;COUNT=10" . "Every other month for 10 occurrences")
      ("FREQ=WEEKLY;BYDAY=MO,WE,FR;COUNT=10" . "Weekly on Monday, Wednesday, Friday for 10 occurrences")
      ("FREQ=YEARLY;BYMONTH=1;BYDAY=SU;COUNT=5" . "Yearly on Sundays in January for 5 occurrences")
      ("FREQ=YEARLY;BYWEEKNO=20;BYDAY=MO" . "Yearly, 20th week, Monday")
      ("FREQ=DAILY;INTERVAL=10;COUNT=5" . "Every 10 days for 5 occurrences")
      ("FREQ=WEEKLY;INTERVAL=2;BYDAY=TU;COUNT=8" . "Every 2 weeks on Tuesday for 8 occurrences")
      ("FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=25" . "Yearly on December 25")
      ("FREQ=DAILY;BYHOUR=9,17;BYMINUTE=30" . "Daily at 9:30 AM and 5:30 PM")
      ("FREQ=MONTHLY;BYDAY=-1SU" . "Monthly on the last Sunday")
      ("FREQ=MONTHLY;BYMONTHDAY=-1" . "Monthly on the last day of the month")
      ("FREQ=DAILY;INTERVAL=2" . "Daily with an interval of 1 day")
      ("FREQ=WEEKLY;BYDAY=SA,SU" . "Weekly on weekends")
      ("FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR" . "Weekly on weekdays")
      ("FREQ=MONTHLY;BYMONTHDAY=15;COUNT=10" . "Monthly on the 15th for 10 occurrences")
      ("FREQ=MONTHLY;BYDAY=1FR" . "Monthly on the first Friday")
      ("FREQ=YEARLY;BYMONTH=4,10;BYDAY=2SU" . "Yearly on the second Sunday of April and October")
      ("FREQ=WEEKLY;COUNT=6;BYDAY=TU,TH" . "Every Tuesday and Thursday for 6 occurrences")
      ("FREQ=YEARLY;BYYEARDAY=1,100,200" . "Yearly on the 1st, 100th, and 200th day of the year")
      ("FREQ=DAILY;BYHOUR=12;BYMINUTE=0;BYSECOND=0" . "Daily at noon")
      ("FREQ=MONTHLY;BYDAY=1MO,-1MO" . "Monthly on the first and last Monday")
      ("FREQ=YEARLY;INTERVAL=4;BYMONTH=2;BYMONTHDAY=29" . "Every 4 years on February 29")
      ("FREQ=MINUTELY;INTERVAL=15;COUNT=96" . "Every 15 minutes for 24 hours")
      ("FREQ=HOURLY;INTERVAL=3;UNTIL=20230501T000000Z" . "Every 3 hours until May 1, 2023")
      ("FREQ=DAILY;BYMINUTE=15,45;BYSECOND=10" . "Daily at 15 and 45 minutes past the hour, 10 seconds in")
      ("FREQ=WEEKLY;BYDAY=MO;BYSETPOS=-1" . "Weekly on the last Monday")
      ("FREQ=MONTHLY;BYDAY=2MO;BYHOUR=8;BYMINUTE=30" . "Monthly on the second Monday at 8:30 AM")
      ("FREQ=YEARLY;BYWEEKNO=1,52;BYDAY=MO" . "Yearly on the first and last week's Monday")
      ("FREQ=MINUTELY;BYSECOND=0,30" . "Every minute at the beginning and half past")
      ("FREQ=DAILY;BYHOUR=0;BYMINUTE=0;BYSECOND=0" . "Daily at midnight")
      ("FREQ=YEARLY;BYDAY=TH;BYWEEKNO=20,-1" . "Yearly on Thursday of the 20th week and last week")
      ("FREQ=MONTHLY;BYMONTHDAY=1,-1;BYHOUR=0;BYMINUTE=0;BYSECOND=0" . "Monthly on the first and last day at midnight")
      ("FREQ=HOURLY;BYMINUTE=0;BYSECOND=0" . "Hourly on the hour")
      ("FREQ=MINUTELY;INTERVAL=30;BYSECOND=10,20,30" . "Every 30 minutes at 10, 20, and 30 seconds in")
      ("FREQ=YEARLY;BYYEARDAY=-365,-1" . "Yearly on the first and last day of the year")
      ("FREQ=MONTHLY;BYDAY=1WE,3WE;BYMONTHDAY=10,20,30" . "Monthly on the 1st and 3rd Wednesday and the 10th, 20th, 30th")
      ("FREQ=YEARLY;BYMONTH=1,6,12;BYDAY=MO,TU,WE,TH,FR" . "Yearly on weekdays of January, June, and December")
      ("FREQ=DAILY;UNTIL=20230402T235959Z;BYSECOND=15,30,45" . "Daily until April 2, 2023, at 15, 30, and 45 seconds past the minute")))
   (error "Test failure")))
